vim-denops/denops.vim

.github/workflows/deno.yml
README.md
autoload/denops/plugin.vim
autoload/denops/server.vim
autoload/denops/server/neovim.vim
autoload/denops/server/vim.vim
denops/denops/cli.ts
denops/denops/context.ts
denops/denops/deps.ts
denops/denops/host/base.ts
denops/denops/host/mod.ts
denops/denops/host/nvim.ts
denops/denops/host/vim.ts
denops/denops/mod.ts
denops/denops/neovim.ts
denops/denops/service.ts
denops/denops/vim.ts

Use Workers instead of processes

---

denops/denops/plugin.ts

Fix Worker URL on Windows

---

denops/denops/deps.ts

Use workerio-deno instead

---

denops/denops/deps.ts

SSIA
Close https://github.com/vim-denops/denops.vim/issues/21
https://user-images.githubusercontent.com/546312/114271590-1d51ee00-9a4d-11eb-95e7-a64dd4a0ed75.mp4

Update workerio to fix massive data issue

---

autoload/denops/lib/job.vim
denops/denops/host/vim.ts

The bug was introduced on #18 
Close https://github.com/vim-denops/denops.vim/issues/23

Fix behavior on Vim

---

.github/workflows/deno.yml
.github/workflows/neovim.yml
.github/workflows/vim.yml

Refactoring CI

---

.github/workflows/deno.yml
.github/workflows/neovim.yml
.github/workflows/reviewdog.yml
.github/workflows/vim.yml

Add `pull_request`

---

.github/workflows/deno.yml

Use denoland/setup-deno instead [re-create]

---

denops/@denops/README.md
denops/@denops/deps.ts
denops/@denops/deps_test.ts
denops/@denops/host/base.ts
denops/@denops/host/nvim.ts

SSIA
Waiting for https://github.com/lambdalisue/msgpack-rpc-deno/pull/12 to fix #34

Add README of deno module and fix type errors

---

.github/workflows/deno.yml
.github/workflows/neovim.yml
.github/workflows/vim.yml

Improve CI

---

.github/workflows/neovim.yml
autoload/denops/server.vim
autoload/denops/server/channel.vim

Fix server issues caused by Async.Promise removal

---

autoload/denops.vim
autoload/denops/plugin.vim
autoload/denops/server.vim
autoload/denops/server/channel.vim
autoload/denops/server/service.vim
autoload/denops/util.vim

Do NOT show debug messages unless g:denops#debug is explicitly assigned

---

.github/workflows/deno.yml
denops/@denops/denops.ts
denops/@denops/test/tester.ts

Add DENOPS_PATH to specify denops.vim and add notes

---

denops/@denops/denops.ts
denops/@denops/denops_test.ts
denops/@denops/test/tester.ts

Add two extra modes 'both' and 'one' on Denops.test

---

denops/@denops-private/service/deps.ts
denops/@denops-private/service/service.ts
denops/@denops-private/service/worker/script.ts

https://twitter.com/takkii/status/1410127506057744385?s=21

🐛  Fix 'Unsupported scheme "c" for module' error on Windows

---

.github/workflows/deno.yml
.github/workflows/neovim.yml
.github/workflows/vim.yml

Improve GitHub Actions

---

autoload/denops/server/service.vim
doc/denops.txt

Enable some debug features when g:denops#debug is enabled

---

Makefile

☕  Add `help` command

---

.github/workflows/deno.yml

☕  Run CI when dlink lockfile is updated

---

.github/workflows/deno.yml

🚿  Reduce the number of jobs in CI

---

denops/@denops-private/service/host/base.ts
denops/@denops-private/service/host/nvim.ts
denops/@denops-private/service/host/vim.ts
denops/@denops-private/service/service.ts
denops/@denops/denops.ts
denops/@denops/denops_test.ts

👍  Add `denops.batch` to batch call Vim/Neovim functions

---

denops/@denops/mod.ts

:+1: Expose missing public types

---

denops/@denops/test/runner.ts
denops/@denops/test/tester.ts

🌿 Properly terminate Vim/Neovim after `test()`

---

autoload/denops/util.vim
denops/@denops-private/channel/deps.ts
denops/@denops-private/service/deps.ts
denops/@denops/denops_test.ts
denops/@denops/deps.ts
denops/@denops/deps_test.ts

To introduce [changes on vim_channel_command](https://github.com/vim-denops/deno-vim-channel-command/pull/8) to fix Vim channel issue like https://github.com/Shougo/ddc.vim/issues/30

:bug: Fix "SyntaxError: Unexpected token X in JSON" error

---

denops/@denops/test/tester.ts
denops/@denops/test/tester_test.ts

I'm hope to using any plugin name at test.
Because request dispatcher is based on plugin name.

🌿Can specify plugin name at test

---

denops/@denops-private/host/invoker.ts

:bug: Fix behavior of `request_async()`

---

autoload/denops/plugin.vim

:bug: Fix "Vim(if) E715 Dictionary required" error

---

README.md

:memo: Change versioning policy

---

denops/@denops/test/tester.ts

Fix OS signal support on Deno 1.14

---

denops/@denops/deps_test.ts
denops/@denops/test/tester.ts

:+1: Simplify `killProcess`

---

autoload/denops/job.vim
autoload/denops/server.vim
autoload/denops/util.vim
doc/denops.txt

Fix denops server

---

.github/workflows/test.yml
.gitignore
README.md
denops/@denops-private/deps.ts
denops/@denops/deps.ts
denops/@denops/deps_test.ts

Re-support Deno v1.11.0

---

autoload/denops/server.vim

:bug: Avoid Neovim stack on server restart

---

.github/workflows/reviewdog.yml
.github/workflows/test.yml

https://docs.github.com/ja/actions/learn-github-actions/workflow-syntax-for-github-actions#jobsjob_idservicesservice_idenv

:coffee: Fix GHA filter pattern

---

Makefile
deno.jsonc

:coffee: Add `deno.jsonc` to ignore `.deno` in lint/fmt

---

autoload/denops.vim
autoload/denops/server.vim
doc/denops.txt

👍  Avoid infinity error restart loop

---

autoload/denops/server.vim
doc/denops.txt

:+1: Simplify restart guard and extend interval to 10 sec

---

denops/@denops/test.ts
denops/@denops/test/bypass/cli.ts

:bug: Fix tests that use `denops.dispatch()` internally

---

denops/@denops-private/worker/script.ts
denops/@denops/test.ts
denops/@denops/test/bypass/cli.ts

:bug: Fix tests

---

denops/@denops-private/cli.ts
denops/@denops-private/worker/script.ts
denops/@denops/test.ts
denops/@denops/test/bypass/cli.ts
denops/@denops/test/tester.ts
denops/@denops/test/tester_test.ts

The output of `make update` is
```
./denops/@denops-private/service.ts
[1/3] Looking for releases: https://deno.land/x/unknownutil@v1.1.4/mod.ts#^
[1/3] Using latest: https://deno.land/x/unknownutil@v1.1.4/mod.ts#^
[2/3] Looking for releases: https://deno.land/x/msgpack_rpc@v3.1.4/mod.ts#^
[2/3] Using latest: https://deno.land/x/msgpack_rpc@v3.1.4/mod.ts#^
[3/3] Looking for releases: https://deno.land/x/workerio@v1.4.3/mod.ts#^
[3/3] Using latest: https://deno.land/x/workerio@v1.4.3/mod.ts#^
./denops/@denops-private/host/invoker.ts
./denops/@denops-private/host/base.ts
[1/1] Looking for releases: https://deno.land/x/disposable@v1.0.2/mod.ts#^
[1/1] Using latest: https://deno.land/x/disposable@v1.0.2/mod.ts#^
./denops/@denops-private/host/vim.ts
[1/2] Looking for releases: …
```

:package: Update Deno dependencies

---

autoload/denops/plugin.vim
denops/@denops-private/worker/script.ts

Fixed the problem that Vim/Neovim freezes when waiting for a motive using `denops#plugin#wait()` in a situation where the plugin fails to initialize.

:bug: Fix Vim/Neovim freeze when `denops#plugin#wait` is used with error

---

autoload/denops/plugin.vim
autoload/denops/util.vim

Fix https://github.com/Shougo/ddu.vim/issues/11

Fix wait condition

---

.github/workflows/reviewdog.yml
.github/workflows/test.yml
.github/workflows/udd.yml

Upgrade `actions/checkout` to v3.

github/workflow: upgrade actions/checkout to v3

---

autoload/denops/server.vim

:bug: Fix channel timeout to 7 days

---

autoload/denops/server.vim

Fix `denops#server#restart()`

---

autoload/denops/plugin.vim
autoload/denops/util.vim

support msys2/cygwin

---

autoload/denops/server.vim
doc/denops.txt
plugin/denops.vim

Improve shared server support

---

autoload/denops/server.vim

No interval was applied on `s:connect`.

:bug: Fix `g:denops#server#reconnect_interval`

---

autoload/denops/plugin.vim
denops/@denops-private/host/invoker.ts
denops/@denops-private/service.ts
denops/@denops-private/worker/script.ts
doc/denops.txt

:bug: Protect server process from "Uncaught (in promise)" error to avoid server death

---

doc/denops.txt

Denops should be developped by vim-denops community.

:memo: Remove `Author` and `License` from help

---

deno.jsonc

See https://github.com/vim-denops/denops.vim/issues/218 for details

:poop: Add `deno.jsonc` as a workaround

---

autoload/denops/server.vim

:bug: Fix "E119: Not enough arguments for function: <SNR>XXX_on_stderr"

---

denops/@denops-private/service.ts

:+1: Allow `null` for convenience

---

denops/@denops-private/service.ts
denops/@denops-private/worker/script.ts

:muscle: Allow a remote URL on `denops#plugin#register()` for testing

---

denops/@denops-private/worker/script.ts

:bug: Import plugin module with fragment

---

autoload/denops.vim
autoload/denops/_internal/server/proc.vim
autoload/denops/plugin.vim
doc/denops.txt

:+1: Add denops#plugin#check_type()

---

denops/@denops-private/impl.ts
denops/@denops-private/impl_test.ts
denops/@denops-private/worker/script.ts
denops/@denops/test/tester.ts

:herb: Fix code in `test` to prepare denops-test module

---

.github/workflows/test.yml
denops/@denops-private/impl_test.ts
denops/@denops/denops.ts
denops/@denops/mod.ts
denops/@denops/test/mod.ts

:herb: Use `denops_test` module instead of (internal) `test` module

---

autoload/denops/_internal/wait.vim

:bug: Fix interruption in Vim on Windows

---

autoload/denops/plugin.vim
denops/@denops-private/worker/script.ts
plugin/denops.vim

🐛 Fix denops#plugin#wait() never complete issue 

---

.github/workflows/test.yml
README.md
autoload/denops.vim
autoload/denops/server.vim
autoload/health/denops.vim
doc/denops.txt
plugin/denops.vim

:boom: Upgrade supported Deno/Vim versions and remove deprecated features

---

README.md

:memo: Add "Support policy" section to README.md

---

denops/@denops-private/cli.ts
denops/@denops-private/error.ts
denops/@denops-private/impl_test.ts
denops/@denops-private/service.ts

:package: Upgrade dependencies and follow up `unknownutil` v3

---

autoload/denops.vim
autoload/denops/plugin.vim
denops/@denops-private/host/invoker.ts
denops/@denops-private/service.ts
denops/@denops-private/worker/script.ts
denops/@denops-private/worker/trace_stream.ts
doc/denops.txt

Trace mode will show messages like

:+1: Add `g:denops#trace`

---

denops/@denops-private/cli.ts
denops/@denops-private/host/nvim.ts
denops/@denops-private/impl_test.ts
denops/@denops-private/service.ts
denops/@denops-private/worker/script.ts
denops/@denops-private/worker/trace_stream.ts

:coffee: Improve trace mode

---

denops/@denops-private/cli.ts
denops/@denops-private/error.ts
denops/@denops-private/host/base.ts
denops/@denops-private/host/invoker.ts
denops/@denops-private/host/nvim.ts
denops/@denops-private/host/vim.ts
denops/@denops-private/impl_test.ts
denops/@denops-private/service.ts
denops/@denops-private/version.ts
denops/@denops-private/worker/patch_console.ts
denops/@denops-private/worker/script.ts

:+1: Minor fixes

---

autoload/denops/plugin.vim
denops/@denops-private/host/invoker.ts
denops/@denops-private/service.ts
denops/@denops-private/worker/script.ts
plugin/denops.vim

:+1: Add `DenopsPluginWorkerPre` and `DenopsPluginWorkerPost`

---

denops/@denops-private/denops_test.ts
denops/@denops-private/host/nvim_test.ts
denops/@denops-private/host/vim_test.ts
denops/@denops-private/host_test.ts
denops/@denops-private/version_test.ts

Only for tests. No changes production code.
Changes to make it more BDD-like.

:herb: improve tests

---

autoload/denops/_internal/plugin.vim
autoload/denops/plugin.vim
doc/denops.txt
tests/denops/runtime/functions/plugin_test.ts
tests/denops/testdata/dummy_plugins/denops/dummy.invalid_name/main.ts

💥 restrict plugin {name}

---

denops/@denops-private/error.ts
denops/@denops-private/host/nvim_test.ts
denops/@denops-private/host/vim_test.ts
denops/@denops-private/host_test.ts
denops/@denops-private/service.ts
denops/@denops-private/service_test.ts
denops/@denops-private/worker.ts
tests/denops/testutil/shared_server.ts
tests/denops/testutil/with.ts

- 📦 Use `@core/streamutil` instead `@lambdalisue/streamtools`.
- 📦 Use `@core/errorutil` instead `@lambdalisue/errorutil`.

Change archived deps

---

.github/workflows/update.yml

- Add pull_request trigger for workflow file changes to validate changes
- Exclude test fixture directory from deno-update-action source files

:coffee: Fix update workflow: test validation and exclude fixture
