denops/denops/host/vim.ts
It's not efficient way thus we will prepare some way to execute commands without `redraw` in #7
=> Send 'redraw' after every 'call' in Vim

autoload/denops.vim, autoload/denops/script.vim, denops/denops/cli/server.ts, denops/denops/deps.ts, denops/denops/host/nvim.ts, denops/denops/host/vim.ts, denops/denops/mod.ts, denops/denops/plugin.ts, denops/denops/service.ts
Now `denops#register()` has deprecated and `mod.ts` files under `denops/xxxxx` directories are loaded as denops plugin automatically.
Deno is a bit slow with typecheck. While typecheck is only required during development, denops disable typecheck in default
https://user-images.githubusercontent.com/546312/108794387-02c0d400-75c9-11eb-8789-6df063d559dd.mp4
=> Automatically load denops plugin and skip typecheck

autoload/denops.vim, autoload/denops/callback.vim, denops/denops/cli/server.ts, denops/denops/host/nvim.ts, denops/denops/host/vim.ts, denops/denops/service.ts
An asynchronous version of `denops#request()`.
For example, users can use it like
```vim
call denops#promise('helloworld', 'echo', ['Hello World'])
\.then({ r -> execute('echomsg r', '') })
\.catch({ e -> execute('echomsg string(e)', '') })
```
=> Add 'denops#promise({plugin}, {func}, {args})` to call denops APIs asynchronously

autoload/denops/script.vim, autoload/denops/server.vim
Now I'm trying to add the feature for inspector and can run inspector now.
I'm simply add `--inspector` flag to callback hooked by `on_channel_opened` if `g:denops#server#inspector_enabled` is `true`.
1. Set `let g:denops#server#inspector_enabled = 1`.
2. Add loop (non-exited process) in any denops plugin.
- I tried it with `Deno.listen` as [my demo](https://github.com/kkiyama117/denops-helloworld.vim) does.
3. Open `v8 inspector`. (like `chrome://inspect`)
4. Open vim and select target of inspector. (`deno - main` is `denops.vim`'s one and each worker is denops plugins' ones.)
5. Run command (like `:DenopsEcho`) and then script is loaded
6. Add breakpoint or click `Pause on Exception` button e.t.c.
- vim has no v8 inspector protocol implementation, so we need to choose or create plugin …
=> Add inspect flag

denops/denops/deps.ts, denops/denops/plugin.ts, denops/denops/service.ts
A new API `dispatch` is added. This is useful for plugin developers who would like to allow 3rd party plugins of the plugin (e.g. Custom source of fuzzy finder like Denite, fzf, telescope, whatever).
The `dispatch` only provides a way to call APIs of other plugins. For example, if you'd like to call an API `echo` of a plugin `alpha` from a plugin `beta`, you can use the following code
```typescript
// From `beta`
await denops.dispatch('alpha', 'echo', []);
```
Note that the plugin `alpha` **must be loaded** prior to call the function above.
Close #30
=> Add `dispatch` to allow plugins to call APIs of other plugins

autoload/denops/plugin.vim
Close #36
After this PR is merged, the following warning message will be shown
```
[denops] The plugin `helloworld` still use `mod.ts` which has deprecated in favor of `app.ts`
```
Plugin authors should rename `mod.ts` to `app.ts` to avoid above warning message.
=> Prefer `app.ts` instead of `mod.ts` as an entrypoint of denops plugin

.github/workflows/deno.yml, denops/@denops/denops.ts, denops/@denops/denops_test.ts, denops/@denops/deps.ts, denops/@denops/test/cli/bypass.ts, denops/@denops/test/runner.ts, denops/@denops/test/tester.ts
Now developers can write tests using denops like
```ts
import { assertEquals } from "./deps_test.ts";
import { Denops } from "./denops.ts";
Denops.test({
mode: 'vim',
name: "test(mode:vim) start vim to test denops features",
fn: async (denops) => {
// Test if `call` works
assertEquals(
await denops.call("has", "nvim") as number,
0,
);
// Test if `cmd` works
await denops.cmd("execute 'let g:denops_test = value'", { value: "Hello World" });
// Test if `eval` works
assertEquals(
await denops.eval("g:denops_test") as string,
"Hello World",
);
},
});
Denops.test('vim', "test(mode:vim) start vim to test denops features", async (denops) => {
// Test if `call` works
assertEquals(
await denops.call("has", "nvim") as number,
0,
);
// Test if `cmd` works
await denops.cmd("execute 'let g:denops_test …
```
=> Add helper function to write tests using denops

.github/workflows/deno.yml
Added a job to do type checking because type checking was not being done in CI.
Currently, there is no subcommand dedicated to type checking, so we use `test --no-run` .
=> Add type check to CI

autoload/denops.vim, autoload/health/denops.vim
It provides supports for Neovim's `:checkhealth` command (and Vim's one, with [rhysd/vim-healthcheck](https://github.com/rhysd/vim-healthcheck) ).
- add `g:denops#version`
- handle `checkhealth`
- check if `deno` is callable from `denops` and check its version.
- check `denops#server` is running.
- check Vim/Neovim version.
- Write docs(README, doc, wiki)
- We may need to determine minimum and recommended version of Vim/Neovim/Deno.
- Some of functions in `health/denops.vim` may be duplicated with `plugin.vim` after #51 is resolved. If you feel it redundant, please merge and move declarations into any other files.
=> Add `checkhealth`

denops/@denops-private/service/service.ts
Denops should support Deno v1.11.0+ so use string instead
https://github.com/denoland/deno/commit/a8e4fc15e516299e9bfc466ae3b2711b6ce2fcd3
=> 🐛  URL specifier for Worker is not supported on Deno v1.11.2

denops/@denops-private/denops.ts, denops/@denops-private/service/worker/script.ts, denops/@denops/denops.ts, denops/@denops/test/tester.ts
Currently, denops.vim exposes `Denops` identifier. It is a `class` so sometimes third-party modules get a type mismatch error by internal implementation details.
This PR aims to solve the problem by expose only `Denops` ***type***,
=> :+1: Expose only types to improve backward compatibility

autoload/denops/plugin.vim, denops/@denops-private/service/host/invoker.ts, denops/@denops-private/service/service.ts, denops/@denops-private/service/worker/script.ts, doc/denops.txt, plugin/denops.vim
To support #75 
See https://github.com/vim-denops/denops.vim/pull/76/files#diff-2dac928d77c51b449506e022e27ca2cf8424241df3bec2a51658ff86ac76cd22 for detail.
Nothing needs to be done. Denops automatically detect if it's loaded after vim startup or not and automatically start server properly
Call `denops#plugin#register('{name}')` with `silent!` like
```vim
silent! call denops#plugin#register('ddc.vim')
```
=> Support lazy loading feature

denops/@denops/deps_test.ts, denops/@denops/test/tester.ts, denops/@denops/test/timeout.ts, denops/@denops/test/timeout_test.ts
Loading https://deno.land/x/timeout@2.4 in denops.vim cause
```
[denops] Unexpected error occured in 'bcdice-api' (C:\home\develop\denops-bcdice-api.vim\denops\bcdice-api\main.ts): TypeError: TS2304 [ERROR]: Cannot find name 'window'.
[denops]   const promise = window.fetch(input, { signal, ...init })
[denops]                   ~~~~~~
[denops]     at https://deno.land/x/abortable@1.6/abort.ts:40:19
```
It's because `abortable` module used in `timeout` module does not support Worker environment
=> 👍  Stop using `timeout` module which cause `TS2304`

autoload/denops/api.vim, autoload/denops/api/vim.vim, denops/@denops-private/service/host/vim.ts, doc/denops.txt
1. Always use a workaround version in Vim so that errors that occurred in Vim become detectable (without `g:denops#debug = 1`)
2. Improve performance of `batch` approx 5 times
=> Improve behavior and performance on Vim

denops/@denops-private/service/defs.ts, denops/@denops-private/service/host/nvim.ts, denops/@denops-private/service/host/vim.ts, denops/@denops-private/service/service.ts, denops/@denops-private/service/worker/script.ts
10 sec is too short for interactive APIs and actually response timeout is not necessary for most of case.
That's why we extend it to 7 days while we think no body leave live Vim session for more than 7 days.
=> 👍  Extend response timeout from 10 sec to 7 days

autoload/denops/api.vim, denops/@denops/denops.ts, denops/@denops/denops_test.ts
Now arguments after `undefined` in `call` or `batch` are dropped for convenience like:
```typescript
test({
mode: "all",
name:
"denops.call() drop arguments after `undefined` (but `null`) for convenience",
fn: async (denops) => {
assertEquals(
await denops.call("denops#api#id", 0, 1, 2),
[0, 1, 2],
);
assertEquals(
await denops.call("denops#api#id", 0, 1, undefined, 2),
[0, 1],
);
assertEquals(
await denops.call("denops#api#id", 0, undefined, 1, 2),
[0],
);
assertEquals(
await denops.call("denops#api#id", 0, 1, null, 2),
[0, 1, null, 2],
);
assertEquals(
await denops.call("denops#api#id", 0, null, 1, 2),
[0, null, 1, 2],
);
},
});
```
```typescript
test({
mode: "all",
name:
"denops.batch() drop arguments after `undefined` (but `null`) for convenience",
fn: async (denops) => {
const …
```
=> 👍  Drop arguments after `undefined` for convenience

denops/@denops-private/channel/cli.ts, denops/@denops-private/channel/deps.ts, denops/@denops-private/service/deps.ts, denops/@denops/deps.ts, denops/@denops/deps_test.ts, denops/@denops/test/bypass/cli.ts
Use `deno_std` instead of `Deno.copy`.
Because `Deno.copy` has been deprecated on `Deno 1.12.0`.
https://deno.com/blog/v1.12#deprecation-of-deno.copy
=> Use `deno_std` instead of `Deno.copy` for fix lint

denops/@denops/test/runner.ts
Stop .swp, etc. from being created in the current directory when buffer changed in testing.
=> 🐛Stop swapfile creation on test

denops/@denops-private/channel/deps.ts, denops/@denops-private/service/deps.ts, denops/@denops/deps.ts, denops/@denops/deps_test.ts
Close #84 by introducing https://github.com/vim-denops/deno-vim-channel-command/pull/7
=> Update dependencies to fix `msgid` bug on Vim

autoload/denops/callback.vim, doc/denops.txt, test/denops/callback.vimspec
Now users can use `denops#callback` module to add persistent callbacks which return results.
=> Improve `denops#callback` module

autoload/denops/api/vim.vim, denops/@denops-private/service/host/vim.ts
=> :+1: Debounce `redraw` after `call` and `batch` on Vim

denops/@denops-private/service/deps.ts, denops/@denops-private/service/host/vim.ts, denops/@denops/denops_test.ts
=> Fix behavior of `denops.call()` when called concurrently on Vim prior to v8.2.3080

autoload/denops/util.vim, doc/denops.txt
=> 📝 Add WARNING for using input() in debug mode

autoload/denops.vim, autoload/denops/server/service.vim, denops/@denops-private/service/cli.ts, denops/@denops-private/service/tracer.ts, doc/denops.txt
=> 👍  Add `g:denops#trace` option to show raw RPC messages

autoload/denops.vim, autoload/denops/api/vim.vim, denops/@denops-private/service/host/vim.ts, denops/@denops/denops_test.ts, denops/@denops/test/tester.ts, doc/denops.txt
The workaround implementation breaks interactive features (such as `input()`) thus the implementation is disabled in default.
This is breaking changes for developers who run tests on Vim 8.2.3081 and want to detect errors. Use `prelude` option to enable the workaround implementation in `test()` like:
```typescript
test({
mode: "vim",
prelude: ["let g: denops#enable_workaround_vim_before_8_2_3081 = 1"],
name: "...",
fn: (denops) => { ... },
});
```
**Note** that this change does not affect behavior for end users. It only affects behavior when `g:denops#debug = 1` or during tests.
=> 💥  Disable workaround implementation for Vim before 8.2.3081 in default

.github/workflows/deno.yml, .github/workflows/vim.yml, README.md, autoload/health/denops.vim, doc/denops.txt, plugin/denops.vim
It seems Vim before 8.2.0662 does not support `input()` function in the channel command, thus we cannot support.
https://github.com/vim/vim/commit/dfc33a665d3b12689aa971575b8e7de4e5202d83
**Note** that denops check Vim/Neovim version on startup from this PR. Disable the feature by the following code if you'd love to use denops on non supported versions.
```vim
let g:denops_disable_version_check = 1
```
=> :boom: Drop support vim before 8.2.0662

autoload/denops/plugin.vim, autoload/denops/server/channel.vim, autoload/denops/server/service.vim, autoload/denops/util.vim, denops/@denops-private/service/host/invoker.ts, denops/@denops-private/service/service.ts, doc/denops.txt
SSIA
Now `reload` option is deprecated. Developers should use `"mode": "reload"` for that.
=> :+1: Add `mode` option and skip duplicated plugins in discovery

autoload/denops/plugin.vim, doc/denops.txt
```
*denops#plugin#is_loaded()*
denops#plugin#is_loaded({name})
Return 1 if a {name} plugin is already loaded. Otherwise return 0.
*denops#plugin#wait()*
denops#plugin#wait({name}[, {options}])
Wait synchronously until a {name} plugin is loaded. It returns
immediately when the {name} plugin is already loaded.
The following attributes are available on {options}.
"interval"	Interval in milliseconds for |sleep| in internal loop.
Default: |g:denops#plugin#wait_interval|
*denops#plugin#wait_async()*
denops#plugin#wait_async({name}, {callback})
Wait asynchronously until a {name} plugin is loaded and invoke a
{callback}. It invokes the {callback} immediately when the {name}
plugin is already loaded. If this function is called multiple times
for same {name} plugin, callbacks registered for the …
```
=> :+1: Add plugin helper functions

autoload/denops.vim, autoload/denops/server.vim, doc/denops.txt
From this version, users need to use the following to get DEBUG and TYPE CHECK mode
```
let g:denops#debug = 1
let g:denops#type_check = 1
```
=> :+1: Add `g:denops#type_check` to enable Deno's type check

autoload/denops.vim, autoload/denops/callback.vim, doc/denops.txt
- Add `denops#callback#register()` and deprecate `denops#callback#add()`
- The default value of `once` option is reversed
- Add `denops#callback#unregister()` and deprecate `denops#callback#remove()`
=> :+1: Refine `denops#callback` module

autoload/denops/callback.vim
This function is deprecated now.
Use denops#callback#unregister() instead.
=> :muscle: Do not use the deprecated denops#callback#remove() function

autoload/denops/api/vim.vim
Adding v:throwpoint.
For example:
```
[denops] Error: Failed to call 'denops#callback#call(c7311ba284c593d5311487b0f0c56ee051787e704444d1644d2a282f55b57901, [object Obje
ct])': function denops#api#vim#call[2]..denops#callback#call[5]..<SNR>89_on_success, 行 1: hoge
```
`function denops#api#vim#call[2]..denops#callback#call[5]..<SNR>89_on_success, 行 1` will be added.
=> :+1: Show the location of the exception when it occurs in the vim

autoload/denops/server.vim
This reverts commit bc3c2e2.
It seems `v:exiting` does not work properly in Neovim thus we need to use `s:vim_exiting` instead at least for Neovim.
https://vim-jp.slack.com/archives/C01N4L5362D/p1632998581482300?thread_ts=1632971053.473400&cid=C01N4L5362D
=> Revert ":+1: Use `v:exiting` instead"

README.md
Thank you so much for putting out this repo, It really cool.
I did follow the readme, it seems to me that he correct command is `:DenopsHello` and not `:HelloDenops`.
=> Fix the denops-helloword.vim command in the readme

denops/@denops-private/cli.ts, denops/@denops-private/worker/script.ts, denops/@denops/test.ts, denops/@denops/test/bypass/cli.ts, denops/@denops/test/tester.ts, denops/@denops/test/tester_test.ts
Because assertThrowsAsync was removed at deno_std 0.118.0
=> Fix assert throws async

autoload/denops/api/vim.vim, doc/denops.txt
The redraw should be removed.  Because it has the side effects.
For example:  `PP ddc#custom#get_current()` does not work well.
I think the redraw is really needed, it should be solved in denops plugins side.
=> Remove debounce redraw

.github/workflows/test.yml, README.md, autoload/health/denops.vim, denops/@denops/test.ts, plugin/denops.vim
The latest version
**Which version should we use?**
- 8.2.2434
- is the version for Ubuntu 20.10
- [for Windows exist](https://github.com/vim/vim-win32-installer/releases/tag/v8.2.2434)
- A years ago... ([2021/01](https://github.com/vim/vim/commit/f2b26bcf8f498fed72759af4aa768fb2aab3118c))
- 8.2.3455
- is the version for MacVim
- for Windows does not exist ([8.2.3452](https://github.com/vim/vim-win32-installer/releases/tag/v8.2.3452) is closest)
- Four month ago ([2021/09](https://github.com/vim/vim/commit/690c524ce6629f9ff67728541ba211f831caf0ee))
The latest version
=> Upgrade supported Vim/Neovim/Deno versions for denops v3

.github/workflows/test.yml, Makefile, README.md, autoload/denops/api/vim.vim, autoload/health/denops.vim, denops/@denops-private/cli.ts, denops/@denops-private/worker/script.ts, denops/@denops/test.ts, denops/@denops/test/bypass/cli.ts, denops/@denops/test/tester.ts, denops/@denops/test/tester_test.ts, doc/denops.txt, plugin/denops.vim
- Developers must call `redraw` manually when `denops#notify()` is used.
- Minimum supported Deno version becomes 1.17.1
- Minimum supported Vim version becomes 8.2.3452
- Minimum supported Neovim version becomes 0.6.0
=> Release denops v3

autoload/denops/plugin.vim, autoload/denops/util.vim, denops/@denops-private/worker/script.ts, doc/denops.txt, plugin/denops/debug.vim
Close #174
- Add a timeout to prevent Vim from freezing forever (-1)
- If the denops server is not ready yet, it will fail immediately (-2)
- Return fail status so that developers can decide to continue (-3)
The best way to use `denops#plugin#wait()` is with early return like
```vim
if denops#plugin#wait('gin')
return
endif
call denops#request('gin', 'status:command', [])
```
=> :bug: Fix `denops#plugin#wait()`

autoload/denops/callback.vim
(CC: @Shougo )
`denops#callback#register()` distinguishes callbacks only by their names, so any [Partials](https://vimhelp.org/eval.txt.html#:~:text=call(Fn%2C%20mylist)-,Partial,-A%20Funcref%20optionally) made from the same function returns the same callback id, whatever their argument is.
`string()` for a funcref returns `function('funcname', [args])` formed string for a Partial, so I think it is preferable for a hash key.
I encountered this problem when I configured [ddu.vim](https://github.com/Shougo/ddu.vim) like following;
```vim
function! s:ddu_cd(command, args) abort
for item in a:args.items
let path = item.action.path
execute a:command .. ' ' .. (isdirectory(path) ? path : fnamemodify(path, ':h'))
endfor
endfunction
call ddu#custom#action('kind', 'file', 'tabnew', …
```
=> Accept Partial for a callback

README.md, autoload/denops/server.vim, denops/@denops-private/cli.ts, denops/@denops-private/service.ts, denops/@denops-private/tee.ts, denops/@denops-private/tee_test.ts, doc/denops.txt, plugin/denops.vim
Start denops global server as follow
```
deno run -A --no-check ./denops/@denops-private/cli.ts
```
Then specify the address to `g:denops_server_addr` prior to Vim startup like
```vim
let g:denops_server_addr = '127.0.0.1:32123'
```
Thanks to @ippachi at vim-jp slack.
https://user-images.githubusercontent.com/546312/172044580-7e2419e7-48f5-419b-b098-35e22bf36208.mov
https://user-images.githubusercontent.com/546312/172044587-cdb47636-beec-41cf-a46f-4c6de81cca40.mov
=> :sparkles: Support a Shared server to avoid the bottleneck of process launches

Makefile, denops/@denops-private/cli.ts, denops/@denops-private/tee.ts, denops/@denops-private/tee_test.ts, denops/@denops-private/worker/script.ts, denops/@denops/test.ts, denops/@denops/test/bypass/cli.ts, denops/@denops/test/tester.ts, denops/@denops/test/tester_test.ts
The output of `make update` is
```
/home/runner/work/denops.vim/denops.vim/denops/@denops-private/tracer.ts
/home/runner/work/denops.vim/denops.vim/denops/@denops-private/tee_test.ts
[1/3] Looking for releases: https://deno.land/std@0.142.0/testing/asserts.ts
[1/3] Attempting update: https://deno.land/std@0.142.0/testing/asserts.ts -> 0.149.0
[1/3] Update successful: https://deno.land/std@0.142.0/testing/asserts.ts -> 0.149.0
[2/3] Looking for releases: https://deno.land/std@0.142.0/streams/mod.ts
[2/3] Attempting update: https://deno.land/std@0.142.0/streams/mod.ts -> 0.149.0
[2/3] Update successful: https://deno.land/std@0.142.0/streams/mod.ts -> 0.149.0
[3/3] Looking for releases: https://deno.land/std@0.142.0/io/mod.ts
[3/3] Attempting update: https://deno.land/std@0.142.0/io/mod.ts …
```
=> :package: Update Deno dependencies

denops/@denops/denops.ts, denops/@denops/impl.ts
Now plugins can use `denops.context` for an instance cache or whatever.
=> Add `context` attribute for plugins

denops/@denops-private/host/base.ts, denops/@denops-private/host/nvim.ts, denops/@denops-private/host/vim.ts, denops/@denops-private/service.ts, denops/@denops/denops.ts, denops/@denops/impl.ts
It seems `redraw` channel command is NOT equivalent to `redraw` command and is required to be invoked on Vim to ensure the correct cursor position.
https://vim-jp.slack.com/archives/C01N4L5362D/p1661433257297529
=> Add `redraw()` to `denops` for Vim

.github/workflows/test.yml
To avoid Node.js 12 actions are deprecated warning
=> :coffee: Upgrade `actions/cache` to v3

autoload/denops.vim, autoload/denops/_internal/echo.vim, autoload/denops/_internal/job.vim, autoload/denops/_internal/meta.vim, autoload/denops/_internal/path.vim, autoload/denops/_internal/wait.vim, autoload/denops/api/vim.vim, autoload/denops/callback.vim, autoload/denops/job.vim, autoload/denops/plugin.vim, autoload/denops/server.vim, autoload/denops/util.vim, autoload/health/denops.vim, denops/@denops-private/cli.ts, denops/@denops-private/host/invoker.ts, denops/@denops-private/service.ts, denops/@denops/test/tester.ts, doc/denops.txt, plugin/denops/debug.vim
I noticed that some denops plugin accidentally use denops's internal features like (`denops#util#....`) so I renamed them to `denops#_internal#...` and make previous functions deprecated.
Additionally, some minor refactorings are applied.
=> :muscle: Refine features in `util` as internal modules and make them deprecated

autoload/denops.vim, autoload/denops/_internal/rpc/nvim.vim, autoload/denops/_internal/rpc/vim.vim, autoload/denops/_internal/server/chan.vim, autoload/denops/_internal/server/proc.vim, autoload/denops/plugin.vim, autoload/denops/server.vim, denops/@denops-private/host/nvim.ts, denops/@denops-private/host/vim.ts, doc/denops.txt, plugin/denops/debug.vim
Close #206 and more
- `DenopsProcessStarted` autocmd that fired when the denops local server is spawned
- `DenopsProcessStopped:{exitcode}` autocmd that fired when the denops local server is stopped
- `DenopsClosed` autocmd that fired when the denops channel is closed. **Recommended way to invoke teardown code**
- `denops#restart()` function to restart a local/shared denops server
- `DenopsStarted` autocmd. Use `DenopsProcessStarted` instead
- `DenopsStopped` autocmd. Use `DenopsClosed` or `DenopsProcessStopped` autocmd
1. Re-initialize your plugin on `DenopsPluginPost:{plugin}` autocmd
2. Tear down your plugin on `DenopsClosed` autocmd if necessary
3. Tear down your plugin on `DenopsStopped` autocmd if necessary for old denops (optional)
=> :boom: Refine server to fix shared server reconnection

autoload/denops/_internal/meta.vim
Note that `v:versionlong` has introduced from Vim 8.1.1526
=> :bug: Fix meta version on non English environment

.github/workflows/test.yml, README.md, autoload/denops/_internal/server/proc.vim, autoload/denops/server.vim, autoload/health/denops.vim, deno.jsonc, doc/denops.txt
- Drop support for Deno prior to v1.28.0
- Type checking is disabled by default since v1.23
- Lockfile is not needed for denops.vim
BTW, should I modify tasks using Deno in Makefile?
=> :+1: Change deno args to follow latest Deno

denops/@denops-private/service.ts, denops/@denops-private/worker/patch_console.ts, denops/@denops-private/worker/script.ts
It's a bit tough work to find which denops plugin shows message like below
```
[denops] [WARN] denops_core: This module is deprecated. Use https://deno.land/x/denops_test/mod.ts instead.
```
With this PR, the message above would look like
```
[denops] [WARN] (gin) denops_core: This module is deprecated. Use https://deno.land/x/denops_test/mod.ts instead.
```
Usually, this kind of hack is bad practice and should be avoided but `console` feature in denops plugin is quite limited due to technical reasons so we decided to forget about grandma's wisdom and fall into the dark side 😈
=> :+1: Patch several methods of `console` to show Worker name for easy debugging

denops/@denops/test/mod.ts
The output is redirected to echomsg so highlight doesn't work anyway.
=> :shower: Do NOT use CSS directive

autoload/denops/server.vim
On older version of Vim (Vim 8.2 bundled on Ubuntu 22.04), `<amatch>` return full-path like `/path/to/DenopsProcessListen:localhost:54321`.
=> handle DenopsProcessListen obscurely

autoload/denops/plugin.vim
We asssumed that this change would improve loading performance of denops plugins.
=> 🚀 Use notify instead to make registration asynchronous

autoload/health/denops.vim
`health#report_XXX` is deprecated in neovim 0.10.
=> Fix for neovim 0.10

denops/@denops-private/error.ts, denops/@denops-private/host/nvim.ts, denops/@denops-private/service.ts, denops/@denops-private/worker/script.ts
Upgrade messagepack_rpc to controll how to serialize/deserialize error object in MessagePack-RPC
Close #259
With `InvokeError` on https://github.com/vim-denops/denops-error-test.vim
```
Error detected while processing function denops#request[1]..denops#server#request[4]..denops#_internal#server#chan#request[4]..denops#_internal#rpc#nvim#request:
line    1:
Error invoking 'invoke' on channel 8:
Error: This is error from denops-error-test.vim
at Object.error (file:///Users/alisue/ghq/github.com/vim-denops/denops-error-test.vim/denops/error-test/main.ts#62.92325:6:13)
at dispatch (https://deno.land/x/messagepack_rpc@v2.0.0/dispatcher.ts:36:36)
at Session.#dispatch (https://deno.land/x/messagepack_rpc@v2.0.0/session.ts:244:28)
at Session.#handleRequestMessage …
```
=> :bug: Fix MessagePack-RPC error handling

denops/@denops-private/cli.ts
Using `await using` cause ambiguous behavior from Deno v1.36.2
https://github.com/denoland/deno/issues/20271
Close #272
=> :bug: Do NOT use `using` to avoid ambiguous behavior

denops/@denops-private/host/nvim.ts
Close #268
https://github.com/neovim/neovim/pull/24399
=> :bug: Use `msgpack-rpc` client type on Neovim

autoload/denops/plugin.vim
Currently `wait_async()` callback is called in loop and using `timer_start()`. It was handled after the loop was turned.
I splited timer call to function. It creates new callstack independent for loop.
Fix #274
=> :bug: Fix always use last callback at `wait_async()`

.github/workflows/update.yml
Use PAT to create a PR to trigger CI, as the original workflow using udd.
I also included another change that replace username for Git commits with "github-actions[bot]", which seems more common. Please discard it if it conflicts with policy of the repository
=> ☕ Fix update workflow

.github/workflows/release.yml
Cause I found it awkward to see the workflow always fails on my fork.
=> ☕ Disable release workflow on forked repositories

autoload/denops/_internal/wait.vim
=> :bug: Do NOT drop consumed input when waiting

autoload/denops.vim, denops/@denops-private/denops.ts, denops/@denops-private/denops_test.ts, denops/@denops-private/host.ts, denops/@denops-private/host/nvim_test.ts, denops/@denops-private/host/vim_test.ts, denops/@denops-private/host_test.ts, denops/@denops-private/service.ts, denops/@denops-private/service_test.ts, doc/denops.txt
Close #307 
- https://github.com/vim-denops/deno-denops-core/pull/8
Create a denops plugin called `interrupt-test` with the following code
```ts
import type { Denops as DenopsOrigin } from "https://deno.land/x/denops_core@v6.0.4/mod.ts";
import { abortable, delay } from "https://deno.land/std@0.211.0/async/mod.ts";
export function main(denops: Denops): void {
denops.dispatcher = {
start: async () => {
const signal = denops.interrupted;
try {
for (let i = 0; i < 100; i++) {
signal.throwIfAborted();
await abortable(denops.cmd(`echo 'Hello ${i}'`), signal);
await delay(100, { signal });
}
} catch (e) {
if (e instanceof DOMException && e.name === "AbortError") {
await denops.cmd("echo 'Interrupted'");
return;
}
throw e;
}
},
};
}
// Assume that Denops v7.0 add `interrupted` attribute to …
```
=> :+1: Add `denops#interrupt()`

autoload/denops/server.vim, tests/denops/plugin_test.ts
If `g:denops_server_addr` is not specified, does not output warning messages on startup.
Outputs below:
```
[denops] denops shared server address (g:denops_server_addr) is not given
```
=> :bug: fix startup message

denops/@denops-private/service_test.ts, tests/denops/plugin_test.ts
Testing `Service` is step-by-step and too complicated.
I organized the tests by method and eliminated dependencies between them.
=> :herb: improve `Service` test

autoload/denops/plugin.vim, tests/denops/runtime/functions/plugin_test.ts, tests/denops/testdata/dummy_plugins/denops/@dummy_namespace/main.ts, tests/denops/testdata/dummy_plugins/denops/dummy_invalid/main.ts, tests/denops/testdata/dummy_plugins/denops/dummy_valid/main.ts
If `denops#plugin#is_loaded()` is called for a plugin that is not loaded, specifying an empty path will cause the `denops#plugin#check_type()` to fail.
If no arguments are specified, the entry whose script is empty will be deleted.
If an argument is specified, no filtering, will occur errors.
=> :bug: prevent error on `denops#plugin#check_type()`

.github/workflows/test.yml, autoload/denops/_internal/echo.vim, autoload/denops/_internal/plugin.vim, denops/@denops-private/service.ts, denops/@denops-private/service_test.ts, doc/denops.txt, tests/denops/runtime/functions/plugin_test.ts, tests/denops/testdata/dummy_invalid_wait_plugin.ts, tests/denops/testdata/dummy_valid_wait_plugin.ts, tests/denops/testutil/shared_server_test.ts
Include fixes #387.
Workflow changed.
- `test` job depends `check` (If `check` failed, `test` does not start.)
- disable `strategy.fail-fast` (If a job failed, do not stop another jobs.)
=> :bug: fix unload feature

.github/workflows/test.yml
Related #396, #397 
Changes to the `supported_versions.json` file now run test CI.
=> :herb: run test CI when any json(c) files changed

.github/workflows/update.yml
Since the current workflow is outdated and can't run: https://github.com/vim-denops/denops.vim/actions/runs/10232085782
Confirmed to run successfully in my fork: 
- Run: https://github.com/hasundue/denops.vim/actions/runs/10232670594/job/28310083039
- PR: https://github.com/hasundue/denops.vim/pull/4
=> :coffee: Migrate `Update` workflow to `molt-action`
